### ISSUE TITLE
Support multi-architecture (ARM64) builds

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/procfile#219]
In order to support multi-architecture builds in the project, we will need to set up buildpacks, builders, and stacks that work on ARM64.

The Procfile is a simple, lightweight first buildpack we could try to enable multi-arch builds for that doesn't require dependencies. As a result, we can use this buildpack to test multi-arch builders down the road.

**Comment by dmikusa** [comment]
I agree. This should not require anything on this repo. Once we get pipeline-builder updated to generate multi-arch images, and update the pipeline in this repo then it should just start publishing multi-arch.

**Comment by jpena-r7** [comment]
Agreed and I think this will be useful to figure out the approach for creating multi-arch buildpacks to be replicated elsewhere.

**Comment by sophiewigmore** [comment]
@dmikusa that's a good point. I'm going to pair up with @anthonydahanne on trying to test out something similar to https://github.com/paketo-buildpacks/syft/pull/204 here, but using the experimental `pack` CLI binary. just to get the ball rolling. We'll contribute it to pipeline-builder when we have something working

**Comment by dmikusa** [comment]
That'd be great! If you get something working in that PR, let me know and I can make those changes in pipeline-builder pretty easily.

**Comment by sophiewigmore** [comment]
experimental multi-arch procfile buildpack available at anthonydahanne/procfile:dual-march15
