### ISSUE TITLE
Provide a Procfile in a binding

### ISSUE THREAD

**Issue by scottfrederick** [paketo-buildpacks/procfile#45]
The procfile buildpack currently detects a `Procfile` in the root of the directory structure provided to the buildpack. This works well in situations where the source code is being provided to the builder and buildpacks are building the application from source. The `Procfile` will be used to influence the image contents but will typically not end up in the generated image. 

With Java applications, it is common for users to build the application and package it as a jar or war file then send the contents of the packaged app to the builder. In this scenario the `Procfile` must be packaged at the root of the jar or war file structure, and will be included in the generated image. This is not ideal, and it would be better if there were an alternate way to expose a `Procfile` to the buildpack.

Since a `Procfile` is intended to contain extra information to influence the generated image but should not be included in the generated image, it seems like a good fit for a binding. Would it be feasible to enhance this buildpack to support detecting the `Procfile` in a binding?

**Comment by dmikusa-pivotal** [comment]
@scottfrederick How do you see this handling multiple Procfiles? Having two sources introduces the possibility that a user could have a file on disk as well as a bound service. 

I feel like we could handle this in a couple of ways:

1. Error if two are present & let the user sort it out
2. Assign some order of precedence, like a map totally overrides a file. So if you have a file & a bound service, the bound service would be used and the file would be ignored & we'd log a message that this happened. (vise versa would be possible too)
3. Read both and try to merge the two. Again, we'd need some order of precedence. Like we load the file first, then load the secret and merge it into the file, such that if you have overlapping commands the command from the higher precedent source wins. For example: with cmd1 of `foo` in the secret and cmd1 of `bar` in the file, you'd end up with `cmd1: foo`, assuming that secret has higher precedence than the file (but again, we could use whatever precedence makes sense). Also, log a message that this happened.

I'm kind of leaning towards #3. It seems most flexible & as long as we alert the user that this happened, it shouldn't surprise anyone. Thoughts?

Thanks
